Pages/Etudiant/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Etudiant
{
    [Authorize(Roles=GestionRole.StudentUser)]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public IndexModel(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public Classe classe { get; set; }
        public IList<Seance> Seances { get; set; }
        public Seance seanceActuel { get; set; }
        public bool etatSeanceActuel { get; set; }

        public IList<SeanceAbsence> modelSeanceAbsence { get; set; }
        public AppUser User { get; set; }
        public async Task OnGetAsync()
        {
            User = await _userManager.GetUserAsync(HttpContext.User);
            var date = DateTime.Now;
            seanceActuel = _context.Seances
                 .Where(s => s.ClasseId == User.ClasseId)
                 .Where(s => s.date >= date && s.date <= date.AddHours(1))
                 .Include(s => s.Classe)
                 .Include(s => s.Matiere)
                 .Include(s => s.Professeur).FirstOrDefault();
            classe = _context.Classes.Find(User.ClasseId);


            Seances = await _context.Seances
                .Where(s => s.ClasseId == User.ClasseId)
                .Where(s => s.date.Day == date.Day)
                .Include(s => s.Classe)
                .Include(s => s.Matiere)
                .Include(s => s.Professeur)
                .ToListAsync();
            modelSeanceAbsence = new List<SeanceAbsence>();
            Absence absence = new Absence();
            SeanceAbsence Inter;
            foreach (var item in Seances)
            {
                Inter = new SeanceAbsence();
                absence = await _context.Absences
                    .Where(s => s.SeanceId == item.Id)
                    .Where(s => s.EtudiantId == User.Id)
                    .FirstOrDefaultAsync();
                Inter.seance = item;
                Inter.absence = absence;
                modelSeanceAbsence.Add(Inter);

                if(seanceActuel!=null && Inter.seance.Id == seanceActuel.Id)
                {
                    etatSeanceActuel = Inter.absence.statut;
                }
            }
        }
        public async Task<IActionResult> OnGetMarquerPresenceAsync(int id)
        {
            User = await _userManager.GetUserAsync(HttpContext.User);
            Absence abs = _context.Absences
                .Where(s=>s.EtudiantId==User.Id)
                .Where(s => s.SeanceId == id)
                .FirstOrDefault();
            if (abs != null)
            {
                abs.statut = false;
                abs.date = DateTime.Now;
                _context.Absences.Attach(abs);
                await _context.SaveChangesAsync();
            }
            return RedirectToPage("./SeancesAvant");
        }
    }
}

Pages/Etudiant/SeancesAvant.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Etudiant
{
    [Authorize(Roles = GestionRole.StudentUser)]
    public class SeancesAvantModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public SeancesAvantModel(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IList<Seance>seances { get; set; }
        public IList<SeanceAbsence> modeleSeanceAbsences { get; set; }
        public AppUser User { get; set; }
        public async Task OnGetAsync()
        {
            User = await _userManager.GetUserAsync(HttpContext.User);
            var date = DateTime.Now;
            seances = await _context.Seances
                .Where(s => s.ClasseId == User.ClasseId)
                .Where(s => s.date.Day < date.Day)
                .Include(s => s.Classe)
                .Include(s => s.Matiere)
                .Include(s => s.Professeur)
                .OrderBy(s=>s.date)
                .ToListAsync();
            modeleSeanceAbsences = new List<SeanceAbsence>();
            Absence absence = new Absence();
            SeanceAbsence Inter;
            foreach (var item in seances)
            {
                Inter = new SeanceAbsence();
                absence = await _context.Absences
                    .Where(s => s.SeanceId == item.Id)
                    .Where(s => s.EtudiantId == User.Id)
                    .FirstOrDefaultAsync();
                Inter.seance = item;
                Inter.absence = absence;
                modeleSeanceAbsences.Add(Inter);

               
            }
        }
    }
}

Pages/Etudiant/Index.cshtml
@page
@model miniProjet.Pages.Etudiant.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h3>@Model.classe.libele</h3>
<a class="btn btn-secondary"   asp-page="SeancesAvant" > << Les seances dernières</a> 

<h3>Les séances programmées pour le : @String.Format("{0 : dddd, MMMM d, yyyy}", DateTime.Now) </h3>
<div class="row">
    <div class="col-md-8">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>
                        Date seance
                    </th>
                    <th>
                        Matiere
                    </th>
                    <th>
                        Professeur
                    </th>
                    <th>
                        Statut
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.modelSeanceAbsence.Count > 0)
                {
                    @foreach (var item in Model.modelSeanceAbsence)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.Matiere.libele)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.Professeur.UserName)

                            </td>
                            <td>
                                @if (item.absence.statut && item.seance.date < DateTime.Now)
                                {
                                    <button type="button" class="btn btn-danger btn-lg" disabled>Absent</button>
                                }
                                else if (!item.absence.statut || (!item.absence.statut && item.seance.date < DateTime.Now))
                                {
                                    <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="@item.absence.date">
                                        <button type="button" style="pointer-events:none;" class="btn btn-success btn-lg">Present</button>
                                    </span>
                                }
                                else
                                {
                                    <span>-----</span>
                                }
                            </td>

                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="text-info"> Aucune séance n'est programmé aujourdhui</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-4">
        @if (Model.seanceActuel != null)
        {
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">Séance en cours</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@Model.seanceActuel.Matiere.libele</h6>
                    <p class="card-text">Vous avez maintenant un cours avec Dr. @Model.seanceActuel.Professeur.UserName</p>
                    @if (Model.etatSeanceActuel)
                    {
                        <a asp-page="Index" asp-page-handler="MarquerPresence" asp-route-id="@Model.seanceActuel.Id" class="btn btn-success">Marquer la présence</a>
                    }
                    else
                    {
                        <p>Vous étes marqué present</p>
                    }


                </div>
            </div>
        }
        else
        {
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title border-info">Vous n'avez pas de cours en ce moment</h5>


                </div>
            </div>
        }
    </div>
</div>

Pages/Etudiant/SeancesAvant.cshtml
@page
@model miniProjet.Pages.Etudiant.SeancesAvantModel
@{
}
<a class="btn btn-info" style="margin-bottom:10px;" asp-page="Index"><< Retour</a>
    <div class="row">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th>
                        Date seance
                    </th>
                    <th>
                        Matiere
                    </th>
                    <th>
                        Professeur
                    </th>
                    <th>
                        Statut
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.modeleSeanceAbsences.Count > 0)
                {
                    @foreach (var item in Model.modeleSeanceAbsences)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.Matiere.libele)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.seance.Professeur.UserName)

                            </td>
                            <td>
                                @if (item.absence.statut && item.seance.date < DateTime.Now)
                                {
                                    <button type="button" class="btn btn-danger btn-lg" disabled>Absent</button>
                                }
                                else if (!item.absence.statut || (!item.absence.statut && item.seance.date < DateTime.Now))
                                {
                                    <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="@item.absence.date">
                                        <button type="button" style="pointer-events:none;" class="btn btn-success btn-lg">Present</button>
                                    </span>
                                }
                                else
                                {
                                    <span>-----</span>
                                }
                            </td>

                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td class="text-info"> Aucune séance n'est programmé aujourdhui</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>