Pages/Administration/Classes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Classes
{
    public class CreateModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public CreateModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Classe Classe { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Classes.Add(Classe);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Administration/Classes/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Classes
{
    public class DeleteModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public DeleteModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Classe Classe { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Classe = await _context.Classes.FirstOrDefaultAsync(m => m.Id == id);

            if (Classe == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Classe = await _context.Classes.FindAsync(id);

            if (Classe != null)
            {
                _context.Classes.Remove(Classe);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Administration/Classes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Classes
{
    public class DetailsModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;
        

        public DetailsModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Classe Classe { get; set; }
        public IEnumerable<AppUser> EtudiantsActuel { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            EtudiantsActuel = await _context.Utilisateurs.Where(s => s.ClasseId == id).OrderBy(s=>s.lastName).ToListAsync();
            Classe = await _context.Classes.FirstOrDefaultAsync(m => m.Id == id);

            if (Classe == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Administration/Classes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Classes
{
    public class EditModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public IEnumerable<AppUser> EtudiantsSansClasse { get; set; }
        public IEnumerable<AppUser> EtudiantsActuel { get; set; }


        public EditModel(miniProjet.Data.ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [BindProperty]
        public Classe Classe { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            EtudiantsSansClasse = await _context.Utilisateurs.Where(s => s.ClasseId == 0).Where(s => s.role == "Etudiant").ToListAsync();
            EtudiantsActuel = await _context.Utilisateurs.Where(s => s.ClasseId == id).Where(s => s.role == "Etudiant").ToListAsync();
            Classe = await _context.Classes.FirstOrDefaultAsync(m => m.Id == id);

            if (Classe == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Classe).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClasseExists(Classe.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }
        public async Task<IActionResult> OnGetAddStudentAsync(string id, int idclasse)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            user.ClasseId = idclasse;
            await _userManager.UpdateAsync(user);
            return RedirectToPage("./Edit", new { id = idclasse });
        }
        public async Task<IActionResult> OnGetRemoveStudentAsync(string id, int idclasse)
        {
            AppUser user = await _userManager.FindByIdAsync(id);
            user.ClasseId = 0;
            await _userManager.UpdateAsync(user);
            return RedirectToPage("./Edit", new { id = idclasse });
        }
        private bool ClasseExists(int id)
        {
            return _context.Classes.Any(e => e.Id == id);
        }
    }
}

Pages/Administration/Classes/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Classes
{
    public class IndexModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public IndexModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Classe> Classe { get;set; }

        public async Task OnGetAsync()
        {
            Classe = await _context.Classes.ToListAsync();
        }
    }
}

Pages/Administration/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using miniProjet.Model;

namespace miniProjet.Pages.Administration
{
    [Authorize(Roles=GestionRole.AdminUser)]
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Administration/Seances/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Seances
{
    public class CreateModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;
        public IList<Matiere> matieres { get; set; }
        public IList<Classe> classes { get; set; }
        public IList<AppUser> professeurs { get; set; }
        public SelectList listMatiers { get; set; }
        public SelectList listClasses { get; set; }
        public SelectList listProfs { get; set; }

        public IList<AppUser> Etudiants { get; set; }

        public CreateModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            matieres = _context.Matieres.ToList();
            classes = _context.Classes.ToList();
            professeurs = _context.Utilisateurs.Where(s=>s.role=="Professeur").ToList();
            listMatiers = new SelectList(matieres, "Id", "libele");
            listClasses = new SelectList(classes, "Id", "libele");
            listProfs = new SelectList(professeurs, "Id", "UserName");

            return Page();
        }

        [BindProperty]
        public Seance Seance { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _context.Seances.Add(Seance);
            await _context.SaveChangesAsync();

            Etudiants = await _context.Utilisateurs.Where(s => s.ClasseId == Seance.ClasseId).ToListAsync();

            Absence abs;

            foreach(var item in Etudiants)
            {
                abs = new Absence();
                abs.EtudiantId = item.Id;
                abs.SeanceId = Seance.Id;
                abs.statut = true;
                _context.Absences.Add(abs);
            }
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Administration/Seances/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Seances
{
    public class DeleteModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public DeleteModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Seance Seance { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Seance = await _context.Seances
                .Include(s => s.Classe)
                .Include(s => s.Matiere)
                .Include(s => s.Professeur).FirstOrDefaultAsync(m => m.Id == id);

            if (Seance == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Seance = await _context.Seances.FindAsync(id);

            if (Seance != null)
            {
                _context.Seances.Remove(Seance);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Administration/Seances/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Seances
{
    public class DetailsModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public DetailsModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Seance Seance { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Seance = await _context.Seances
                .Include(s => s.Classe)
                .Include(s => s.Matiere)
                .Include(s => s.Professeur).FirstOrDefaultAsync(m => m.Id == id);

            if (Seance == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Administration/Seances/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Seances
{
    public class IndexModel : PageModel
    {
        private readonly miniProjet.Data.ApplicationDbContext _context;

        public IndexModel(miniProjet.Data.ApplicationDbContext context)
        {
            _context = context;
        }
        public string nameOfMatiere(int MatiereId)
        {
            var query = from s in _context.Matieres
                        where s.Id == MatiereId
                        select new
                        {
                            libele = s.libele
                        };
            return query.FirstOrDefault().libele;
        }
        public IList<Seance> Seance { get;set; }
        

        public async Task OnGetAsync()
        {
            Seance = await _context.Seances
                .OrderByDescending(s=>s.date)
                .Include(s=>s.Matiere)
                .Include(s=>s.Classe)
                .Include(s=>s.Professeur)
                .ToListAsync();
            
            
        }
    }
}

Pages/Administration/Users/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using miniProjet.Data;
using miniProjet.Model;

namespace miniProjet.Pages.Administration.Users
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public IList<AppUser> students { get; set; }
        public IList<AppUser> teachers { get; set; }
        public IList<AppUser> admins { get; set; }
        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            admins = _context.Utilisateurs.ToList();


        }
    }
}

Pages/Administration/Classes/Create.cshtml
@page
@model miniProjet.Pages.Administration.Classes.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Classe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Classe.libele" class="control-label"></label>
                <input asp-for="Classe.libele" class="form-control" />
                <span asp-validation-for="Classe.libele" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Administration/Classes/Delete.cshtml
@page
@model miniProjet.Pages.Administration.Classes.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Classe</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Classe.libele)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Classe.libele)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Classe.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Administration/Classes/Details.cshtml
@page
@model miniProjet.Pages.Administration.Classes.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h3>Classe</h3>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Classe.libele)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Classe.libele)
        </dd>
    </dl>
    <h4>Les etudiants de cette classe</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nom complet
                </th>
                <th>
                    Email
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.EtudiantsActuel)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Classe.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Administration/Classes/Edit.cshtml
@page
@model miniProjet.Pages.Administration.Classes.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Classe</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Classe.Id" />
            <div class="form-group">
                <label asp-for="Classe.libele" class="control-label"></label>
                <input asp-for="Classe.libele" class="form-control" />
                <span asp-validation-for="Classe.libele" class="text-danger"></span>
            </div>
            <p>
                <a class="btn btn-success" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Afficher les etudiants de cette classe</a>
                <button class="btn btn-success" type="button" data-toggle="collapse" data-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Afficher les etudiants qui n'ont pas de classe</button>
                <button class="btn btn-success" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Afficher tout</button>
            </p>
            <div class="row">
                <div class="col">
                    <div class="collapse multi-collapse" id="multiCollapseExample1">
                        <div class="card card-body">
                            <div class="form-group">
                                <label class="control-label">Les etudiants de cette classe</label>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Nom complet
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach(var item in Model.EtudiantsActuel)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem=>item.UserName)
                                                </td>
                                                <td>
                                                    <a class="btn btn-danger" asp-page="Edit" asp-page-handler="RemoveStudent" asp-route-id="@item.Id" asp-route-idclasse="@Model.Classe.Id">Retirer</a>

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="collapse multi-collapse" id="multiCollapseExample2">
                        <div class="card card-body">
                            <div class="form-group">
                                <label class="control-label">Les etudiants qui n'ont pas de classe</label>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>
                                                Nom complet
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.EtudiantsSansClasse)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.UserName)
                                                </td>
                                                <td>
                                                  <a class="btn btn-info" asp-page="Edit" asp-page-handler="AddStudent" asp-route-id="@item.Id" asp-route-idclasse="@Model.Classe.Id">Ajouter</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Administration/Classes/Index.cshtml
@page
@model miniProjet.Pages.Administration.Classes.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Classe[0].libele)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Classe) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.libele)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>